x-healthcheck: &healthcheck
  interval: 2s
  timeout: 3s
  retries: 5
  start_period: 2s

x-python-env: &python-env
  PYTHONUNBUFFERED: 1
  PYTHONIOENCODING: UTF-8

configs:
  wan.json:
    content: |
      {
          "dt": "2022-01-20T12:57:59.823350+00:00",
          "wan": {
              "dt": "2022-01-20T12:57:59.823350+00:00",
              "curls": ["http://${WITNESS_DEMO_HOSTNAME:-localhost}:5642/"]
          }
      }
  wil.json:
    content: |
      {
          "dt": "2022-01-20T12:57:59.823350+00:00",
          "wil": {
              "dt": "2022-01-20T12:57:59.823350+00:00",
              "curls": ["http://${WITNESS_DEMO_HOSTNAME:-localhost}:5643/"]
          }
      }
  wes.json:
    content: |
      {
          "dt": "2022-01-20T12:57:59.823350+00:00",
          "wes": {
              "dt": "2022-01-20T12:57:59.823350+00:00",
              "curls": ["http://${WITNESS_DEMO_HOSTNAME:-localhost}:5644/"]
          }
      }
  keria.json:
    content: |
      {
          "dt": "2023-12-01T10:05:25.062609+00:00",
          "keria": {
              "dt": "2023-12-01T10:05:25.062609+00:00",
              "curls": ["http://keria:3902/"]
          },
          "iurls": [
              "http://witness-demo:5642/oobi/BBilc4-L3tFUnfM_wJr4S4OJanAv_VmF_dJNN6vkf2Ha/controller",
              "http://witness-demo:5643/oobi/BLskRTInXnMxWaGqcpSyMgo0nYbalW99cGZESrz3zapM/controller",
              "http://witness-demo:5644/oobi/BIKKuvBwpmDVA4Ds-EpL5bt9OqPzWPja2LigFYZN2YfX/controller"
          ]
      }

services:
  keria:
    build: ./
    environment:
      <<: *python-env
    configs:
      - source: keria.json
        target: /keria/config/keri/cf/keria.json
    command: start --config-dir /keria/config --config-file keria --name agent
    ports:
      - 3901:3901
      - 3902:3902
      - 3903:3903
    healthcheck:
      test: curl http://localhost:3902/health
      <<: *healthcheck

  vlei-server:
    image: gleif/vlei:0.2.0
    environment:
      <<: *python-env
    command: vLEI-server -s ./schema/acdc -c ./samples/acdc/ -o ./samples/oobis/
    healthcheck:
      test: curl -f http://localhost:7723/oobi/EBfdlu8R27Fbx-ehrqwImnK-8Cm79sqbAQ4MmvEAYqao
      <<: *healthcheck
    ports:
      - 7723:7723

  witness-demo:
    image: weboftrust/keri-witness-demo:1.1.0
    environment:
      <<: *python-env
    healthcheck:
      test: curl -f http://localhost:5642/oobi
      <<: *healthcheck
    configs:
      - source: wan.json
        target: /keripy/scripts/keri/cf/main/wan.json
      - source: wes.json
        target: /keripy/scripts/keri/cf/main/wes.json
      - source: wil.json
        target: /keripy/scripts/keri/cf/main/wil.json
    ports:
      - 5642:5642
      - 5643:5643
      - 5644:5644
