name: GitHub Actions for Signify TS

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Lint changes
        run: npm run lint

      - name: Check formatting
        run: npm run format:check

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Build docker
        run: docker compose up --build --wait
        env:
          WITNESS_DEMO_HOSTNAME: witness-demo
          VLEI_SERVER_HOSTNAME: vlei-server

      - name: Run integration test
        run: npm run test:integration
        env:
          WITNESS_DEMO_HOSTNAME: witness-demo
          VLEI_SERVER_HOSTNAME: vlei-server
